services:
  node:
    container_name: ennoble-x-auth
    networks:
      - backend
    build:
      args:
        TZ: ${TZ}
      context: node
    tty: true

    volumes:
    - ../:/app:rw
    command: >
      sh -c "yarn && yarn start"
version: '3.7'
networks:
  backend:
    driver: bridge
    name: ennoble-x-net
