version: '3.7'
services:
  node:
    env_file:
      - .env
    networks:
      - backend
    ports:
    - 300:${PORT}
    build:
      args:
        TZ: ${TZ}
      context: node
    tty: 'true'
    volumes:
    - ../:/app:rw
    - ./logs/node:/var/log/ennoble-x
    command: >
      sh -c "yarn
      && yarn start"
  nginx:
    container_name: ennoble-x-web
    networks:
      - backend
    build:
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        TZ: ${TZ}
      context: nginx
    env_file:
      - .env
    volumes:
    - ./logs/nginx/:/var/log/nginx
    - ./nginx/sites:/etc/nginx/conf.d
    - ../:/app:rw
    #command: /bin/sh -c "envsubst < /etc/nginx/conf.d/local.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
networks:
  backend:
    driver: bridge
    name: ennoble-x-net
